### ISSUE TITLE
Swift 3.0 Version

### ISSUE THREAD

**Issue by Ged2323** [jasonpaulwong/SwiftGameCenter#1]
Hi any chance you would be able to have a look at this and convert it to Swift 3.0. 
Thanks in advance for your help.

**Comment by jasonpaulwong** [comment]
Sorry, I just tried relooking at the code and I believe a lot of the code is clearly outdated (i.e. the Object C naming conventions, which I copied from the tutorial), not just the Swift version itself. I had written this code when I first started programming in Swift so I would not recommend using it.

Also, I don't have access to the game that I used to test this code so I wouldn't be able to test it either to ensure it works properly.

As such, I found this may be better for what you are looking for:
https://github.com/YannickSteph/Easy-Game-Center-Swift

**Comment by Ged2323** [comment]
Ok no worries.  Thanks for the link.  I’m working on EGC one atm.  :) Thank you
